version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      frontend-major:
        patterns:
          - "*"
        update-types:
          - "major"
      frontend-minor-patch:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      backend-major:
        patterns:
          - "*"
        update-types:
          - "major"
      backend-minor-patch:
        patterns:
          - "*"
