services:
  db:
    image: postgres:16.13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kalneslopene
    ports:
      - "5432:5432"
    volumes:
      - kalnes_db:/var/lib/postgresql/data

  backend:
    build: ./backend/Dockerfile
    env_file:
      - path: .env

volumes:
  kalnes_db:
