INSERT INTO newsfeed (uuid, tags, header, content, date)
VALUES (gen_random_uuid(),
        ARRAY ['løp', 'sesong'],
        'Ny sesong starter i januar!',
        'Vi er glade for å ønske alle løpere velkommen til en ny sesong med Kålnesløpene! Første løp er satt til 8. januar 2026. Møt opp kl. 18:00 ved start i Kålnes. Husk å registrere deg på forhånd.',
        TIMESTAMP '2025-12-15 10:00:00'),
       (gen_random_uuid(),
        ARRAY ['resultater', 'løp'],
        'Resultater fra løp #3 er publisert',
        'Takk til alle som deltok i torsdagsløpet! Det var 42 påmeldte og flotte forhold på løypa. Resultater finner du under Resultater-fanen. Gratulerer til alle som satte personlig rekord!',
        TIMESTAMP '2026-01-22 20:30:00'),
       (gen_random_uuid(),
        ARRAY ['løype', 'info'],
        'Endring i løypa for neste uke',
        'Grunnet veiarbeid ved Kålnes gård vil løypa for løp #5 bli noe justert. Ny løype er totalt 4,2 km og starter som vanlig kl. 18:00. Kart over ny løype finner du under Løypekart.',
        TIMESTAMP '2026-02-03 14:00:00'),
       (gen_random_uuid(),
        ARRAY ['arrangement', 'jubileum'],
        'Kålnesløpene fyller 10 år – feiring etter løpet!',
        'I år markerer vi 10 år med torsdagsløp! Etter løp #8 inviterer vi alle deltakere og frivillige til en liten feiring med kaffe og kake. Ta med familie og venner – alle er hjertelig velkomne.',
        TIMESTAMP '2026-02-20 09:00:00'),
       (gen_random_uuid(),
        ARRAY ['frivillig', 'hjelp'],
        'Vi trenger flere frivillige!',
        'For å kunne gjennomføre løpene trenger vi hjelp fra frivillige til å bemanne poster og hjelpe til med tidtaking. Har du lyst til å bidra? Ta kontakt med oss via kontaktskjemaet eller kom innom i starten.',
        TIMESTAMP '2026-03-01 11:00:00'),
       (gen_random_uuid(),
        ARRAY ['resultater', 'statistikk'],
        'Halvsesongen er unnagjort – se statistikken!',
        'Vi har nå gjennomført 6 av 12 løp i sesongen. Besøk Statistikk-siden for å se hvem som leder sammenlagt, gjennomsnittlige tider og mye mer. Spennende jevnbyrdighet i år!',
        TIMESTAMP '2026-03-10 18:45:00');

