spring:
  application:
    name: kalneslopene
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    drop-first: false
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
