spring:
  application:
    name: kalneslopene
  datasource:
    url: jdbc:postgresql://localhost:5432/torsdagslopet
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:db/changelog/changelog-local.yaml
  jpa:
    hibernate:
      ddl-auto: none
