spring:
  application:
    name: kalneslopene
  liquibase:
    drop-first: false
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
